name: Security Review

permissions:
  pull-requests: write # Needed for leaving PR comments
  contents: read

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 2

      - uses: karasHou/claude-code-security-review@main
        with:
          comment-pr: true
          # claude-api-key: ${{ secrets.CLAUDE_API_KEY }}
          claude-auth-token: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          claude-base-url: ${{ vars.ANTHROPIC_BASE_URL }}
